### PR TITLE
Implement state locking with dynamo-db

### PR DESCRIPTION
**Pull request by mat285**

### CODE REVIEW

**Comment by mat285** [comment]
Yep! Makes sense! I'd be happy to change that to optional rather than required

**Comment by mat285** [comment]
Should be optional now. It seems I'm failing the ci build since my repo is forked

**Comment by mat285** [comment]
@ryanking I tried merging master for the travis change and its still failing. Any guidance here?

**Comment by ryanking** [comment]
@mat285 - not sure, looking to see what we're doing wrong here

**Comment by ryanking** [comment]
@mat285 this should fix. feel free to merge to your branch

**Comment by mat285** [comment]
@ryanking I'm not authorized to merge it. Could you do it please?

**Pull request merged**
